---
name: Auto-Approve Bot
description: Automatically approve pull requests from configured bots with specific triggers
branding:
  icon: check-circle
  color: green
inputs:
  github-token:
    description: GitHub token with permissions to approve pull requests
    required: true
    default: ${{ github.token }}
  config-path:
    description: Path to the configuration file
    required: false
    default: .github/auto-approve.yml
runs:
  using: node20
  main: dist/index.js
