autoInstallPeers: true
dedupePeerDependents: true
savePrefix: ''
shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: true

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver

overrides:
  jiti: <2.2.0
