---
name: GitHub App

on:
  issues:
    types:
      - opened

permissions:
  contents: read

jobs:
  issuesOpened:
    name: Issues opened
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          run_install: false
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          cache: pnpm
          node-version-file: package.json
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm build
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
