---
name: GitHub App
'on':
  issues:
    types:
      - opened
jobs:
  issuesOpened:
    name: Issues opened
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: corepack enable
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          cache: pnpm
          node-version-file: package.json
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm build
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
