---
name: GitHub App
'on':
  issues:
    types:
      - opened
jobs:
  issuesOpened:
    name: Issues opened
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - run: corepack enable
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          cache: pnpm
          node-version-file: package.json
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm build
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
