---
name: CI
'on':
  push:
    branches: [main, 'renovate/**']
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          cache: yarn
          node-version-file: package.json
      - run: yarn install --immutable
      - name: Check formatting
        run: yarn prettier --check .
      - run: yarn test
