---
name: CI

'on':
  push:
    branches: [main, 'renovate/**']
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: corepack enable
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          cache: pnpm
          node-version-file: package.json
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Check formatting
        run: pnpm check-format
      - run: pnpm test

  release:
    env:
      DRY_RUN: ${{ github.ref_name != github.event.repository.default_branch }}
    name: Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - id: get-workflow-access-token
        name: Get Workflow Access Token
        uses: peter-murray/workflow-application-token-action@dc0413987a085fa17d19df9e47d4677cf81ffef3 # v3.0.0
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          permissions: 'contents:write, issues:write, pull_requests:write'
      - name: Setup Git user
        run: |
          git config --global user.email '118100583+bfra-me[bot]@users.noreply.github.com'
          git config --global user.name 'bfra-me[bot]'
      - name: Checkout `release` branch
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          ref: release
          token: ${{ steps.get-workflow-access-token.outputs.token }}
      - if: ${{ github.event_name == 'pull_request' }}
        name: Fetch PR
        run: git fetch origin +${{ github.sha }}:${{ github.ref }}
      - id: merge
        name: Merge `main` into `release`
        run: |
          git merge --no-ff -Xtheirs -m 'skip: merge (${{ github.sha }}) [skip release]' ${{ github.sha }}
          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          cache: pnpm
          node-version-file: package.json
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - if: env.DRY_RUN != 'true'
        name: Push `release` branch
        run: git push origin release:release
      - env:
          GIT_AUTHOR_EMAIL: '118100583+bfra-me[bot]@users.noreply.github.com'
          GIT_AUTHOR_NAME: 'bfra-me[bot]'
          GIT_COMMITTER_EMAIL: '118100583+bfra-me[bot]@users.noreply.github.com'
          GIT_COMMITTER_NAME: 'bfra-me[bot]'
          GITHUB_TOKEN: ${{ steps.get-workflow-access-token.outputs.token }}
        id: semantic-release
        name: Semantic Release
        run: |
          export GITHUB_REF=refs/heads/release GITHUB_SHA=${{ steps.merge.outputs.commit }}
          pnpm semantic-release --dry-run ${{ env.DRY_RUN }} --ci ${{ env.DRY_RUN != 'true' }}
      - if: github.event_name == 'push' && env.DRY_RUN != 'true'
        run: 'git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git refs/heads/release:refs/heads/v1'
        env:
          GITHUB_TOKEN: ${{ steps.get-workflow-access-token.outputs.token }}
