---
name: CI
'on':
  push:
    branches: [main, 'renovate/**']
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          cache: yarn
          node-version-file: '.node-version'
      - run: yarn install --immutable
      - run: yarn test
