---
name: Release
'on':
  push:
    branches: [main]

env:
  FORCE_COLOR: true

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          cache: yarn
          node-version-file: '.node-version'
      - run: yarn install --immutable
      - run: yarn build
      - run: rm .gitignore # dist/ folder is ignored by default
      - run: yarn dlx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
