---
name: Release
'on':
  push:
    branches: [main]

env:
  FORCE_COLOR: true

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          cache: yarn
          node-version-file: package.json
      - run: yarn install --immutable
      - run: yarn build
      - name: Get Workflow Access Token
        id: get-workflow-access-token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # v2.1.0
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
      - uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3.8.0
        with:
          node-version: 'lts/*'
      - run: yarn dlx semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.get-workflow-access-token.outputs.token }}
      - run: 'git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/v1'
        env:
          GITHUB_TOKEN: ${{ steps.get-workflow-access-token.outputs.token }}
