# Update repository settings to match the definitions in .github/settings.yml.
---
name: Update Repo Settings

on:
  push:
    branches: [main]
  schedule:
    - cron: '37 17 * * *' # Every day at 17:37 UTC
  workflow_dispatch:

jobs:
  update-repo-settings:
    name: Update Repo Settings
    secrets: inherit
    uses: bfra-me/.github/.github/workflows/update-repo-settings.yaml@6e301c16a0c34c6650b3c637f215c5c57c9ee0d9 # v4.16.29
